// Generated by CoffeeScript 1.4.0
var fluid, variadic;

variadic = require('../decorators/variadic');

fluid = require('../decorators/fluid');

module.exports = function(klazz) {
  return klazz.prototype.returning = fluid(variadic(function(cols) {
    this.q.addReturning(cols);
    return this;
  }));
};
