// Generated by CoffeeScript 1.4.0

module.exports = function(fn, msg) {
  return function() {
    console.warn('DEPRECATED: ', msg, new Error().stack.split('\n').slice(1).join('\n'));
    return fn.apply(this, arguments);
  };
};

module.exports.rename = function(fn, oldName, newName) {
  return module.exports(fn, "" + oldName + " has been renamed to " + newName + " and will be removed in a future release.");
};
