// Generated by CoffeeScript 1.4.0

module.exports = function(method) {
  return function(first) {
    if (Array.isArray(first)) {
      return method.call(this, first);
    } else {
      return method.call(this, Array.prototype.slice.call(arguments));
    }
  };
};
